.rubocop.yml
lib/iiif_print.rb

- remove mentions of page_finder to unblock generator install
ref https://github.com/scientist-softserv/iiif_print/pull/5

remove mentions of page_finder since it was removed

---

iiif_print.gemspec

- downgrade `dry-monads` to 1.4

downgrade dry monads to 1.4

---

iiif_print.gemspec
spec/spec_helper.rb

ref https://github.com/scientist-softserv/iiif_print/issues/7

Update gemspec to get spec_helper working

---

lib/iiif_print.rb
spec/iiif_print_spec.rb

See examples, specs, and documentation.

Exposing `IiifPrint.model_configuration` method

---

app/search_builders/concerns/iiif_print/exclude_models.rb
lib/generators/iiif_print/templates/config/initializers/iiif_print.rb
lib/iiif_print/configuration.rb
spec/search_builders/custom_search_builder_spec.rb

ref #12 
- add configuration to `#exclude_models`
- update specs
- update config template

I12 genericize exclude models

---

.github/workflows/build-test-lint.yaml

Thanks for your guidance @aprilrieger 🎉 
PS. The test passing is misleading and does not reflect the actual status of the spec suite

[i44] add build-test-lint.yaml

---

lib/iiif_print/data/work_files.rb
spec/lib/iiif_print/data/work_files_spec.rb
spec/misc_shared.rb

ref #38 
- bring over fix from LV
- make specs pass

[i38] - add WorkFiles fix from LV and fix specs

---

lib/iiif_print/text_extraction_derivative_service.rb

Prior to this commit, we had a duplication of logic regarding the three types of files we were creating from the alto generation (e.g. xml, txt, and json).
These are always written and stored as derivatives.  Which is unlikely to be desirous behavior in all cases.
With this commit, I'm exposing three configuration points with the primary one being which formats we choose to call and their corresponding methods on the OCR derivation file.

Extracting class attributes to improve configurability

---

app/services/iiif_print/pluggable_derivative_service.rb

In a first step to towards disentangling derivative creation, we do a small refactor for our `PluggableDerivativeService`.  The `#valid?` method should not always return true and instead will ask if we have any plugins.
ref: https://github.com/scientist-softserv/utk-hyku/issues/343

PluggableDerivativeService refactor

---

app/actors/iiif_print/actors/file_set_actor_decorator.rb
lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb

This helps pass tests in Essi and should be a no op change for IIIF Print.

Bail earlier

---

.github/workflows/build-lint-test-action.yaml
spec/iiif_print/data/work_derivatives_spec.rb

This pr updates the version of github actions, to pull in the fix for failing specs: https://github.com/scientist-softserv/actions/pull/36
ref: https://github.com/scientist-softserv/dev-ops/issues/610

failing tests should break the pipeline

---

lib/iiif_print/split_pdfs/pages_into_images_service.rb
lib/iiif_print/split_pdfs/pdf_image_extraction_service.rb

c1fd2af09bf3cff394b514ffe29c9e48d02c7f5e
Prior to this commit, the PagesIntoImagesService class had a confusing
method read order.  If you started from the bottom and read upward, you
might encounter the methods that were referenced in the bottom most
method.
With this commit, I'm doing a few things:
1. Removing commented out code
2. Favoring attr_reader over instance methods
3. Adding some documentation to explain intention
4. Narrowing the objects’ public interfaces
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/293
34bffa9a3efb52b8825f76fd16f9710dbfaee5ea
This commit does a few things:
1. Renames a method to add `?` (thus improving legibility)
2. Restructures the boolean logic to read more smoothly
3. Removes multiple loops, favoring faster processes
4. Favor a …

Refactoring low-level classes for legibility

---

app/services/iiif_print/manifest_builder_service_behavior.rb

ref: https://github.com/scientist-softserv/iiif_print/issues/153
Previously this only supported a Hyku paradigm but we also have Hyrax only clients to consider.  Some of the methods are named different and this will account for that.

Adding support for Hyrax

---

app/presenters/iiif_print/iiif_manifest_presenter_factory_behavior.rb

This is just a quality of life refactor found another spot to contend with.
related to: https://github.com/scientist-softserv/iiif_print/commit/444b95f62235d2f1b4a1d83cce0880b47d30ec59

Refactor another `#file_set_ids`

---

app/services/iiif_print/manifest_builder_service_behavior.rb
lib/iiif_print/metadata.rb
spec/iiif_print/metadata_spec.rb

This commit mainly brings metadata support for version 3 manifests. We also change the fact that we are working with a `SolrHit` vs a `SolrDocument` and account for that in a few places.  Instead of doing `work.title`, we now do `work['title_tesim']`.
<details>
<summary>Manifest</summary>
```json
{
"@context": [
"http://www.w3.org/ns/anno.jsonld",
"http://iiif.io/api/presentation/3/context.json"
],
"type": "Manifest",
"id": "https://mola.bl.test/concern/images/ceb7f503-ff7f-44db-b93b-d751c2239c69/manifest",
"label": {
"none": [
"The Star Wars Movies"
]
},
"service": [
{
"@context": "http://iiif.io/api/search/1/context.json",
"profile": "http://iiif.io/api/search/1/search",
"label": "Search within this manifest",
"type": "SearchService1",
"id": …
```

Add support for presentation v3 metadata

---

app/services/iiif_print/manifest_builder_service_behavior.rb
lib/iiif_print/configuration.rb
spec/iiif_print/configuration_spec.rb
spec/services/iiif_print/manifest_builder_service_behavior_spec.rb

Addresses https://scientist-inc.sentry.io/issues/4005245627/

Ensuring version is set earlier in instantiation

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This will help us to follow best practices. Updates per playbook article: https://playbook-staging.notch8.com/en/git/github-issue-pr-templates

Add issue and PR templates to project

---

app/services/iiif_print/manifest_builder_service_behavior.rb

Switch to :post method to remove error 414 `Request-URI Too Long Error`
Add pagination through id list to avoid potential error when > 1024 boolean conditions (see https://solr.apache.org/guide/8_1/query-settings-in-solrconfig.html#maxbooleanclauses)
Restructure code so each item doesn't re-do the query.
Refs #224 
Manifest errors for work with many pages.
UV displays for work with many pages.
<details>
</details>

Modify solr query for children

---

.gitignore

These are cluttering up my search results

🎬 Adding more files to the gitignore

---

app/services/iiif_print/derivative_rodeo_service.rb
lib/iiif_print/engine.rb
lib/iiif_print/jobs/child_works_from_pdf_job.rb
spec/services/iiif_print/derivative_rodeo_service_spec.rb

Adding a class that implements that Hyrax::DerivativeService and makes the necessary assumptions about how we are creating derivatives using the rodeo.
There are lots of comments and todos that are a short-cut.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/219
- https://github.com/scientist-softserv/iiif_print/pull/243

🎁 Adding IiifPrint::DerivativeRodeoService

---

lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb

Cherry-pick additional commit from no_rodeo branch. 
Ref https://github.com/scientist-softserv/iiif_print/pull/256
<details>
</details>

🐛 Fix typo `default` to `default_coords`

---

app/search_builders/concerns/iiif_print/allinson_flex_fields.rb
app/search_builders/concerns/iiif_print/iiif_search_builder_decorator.rb
lib/iiif_print/catalog_search_builder.rb
lib/iiif_print/engine.rb

If `AllinsonFlex` is defined in an application, this commit will add the ability to add `AllinsonFlex` fields to the the catalog search and IIIF search.

🎁 Add `AllinsonFlex` fields to solr queries

---

lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb

This commit will fix a bug where the query was matching cases.

🐛 Fix case insensitive query

---

lib/iiif_print/jobs/create_relationships_job.rb

found this code - sorry I couldn't find it earlier

make target count part of the error message for children

---

README.md
lib/generators/iiif_print/templates/config/initializers/iiif_print.rb
lib/iiif_print.rb

Related to:
- https://github.com/scientist-softserv/adventist-dl/pull/673

📚 Add documentation regarding DerivativeRodeo

---

lib/iiif_print/version.rb

Update version to 2.0.1

---

app/listeners/iiif_print/listener.rb
app/services/iiif_print/derivative_rodeo_service.rb

This should've gone along with the original PR. Other places needed this. 
- https://github.com/scientist-softserv/iiif_print/pull/356

:broom: add defensive programming

---

app/jobs/iiif_print/jobs/child_works_from_pdf_job.rb

Refs https://github.com/scientist-softserv/palni_palci_knapsack/pull/103
Resource_type is handled similarly to title, outside of attributes in Hyrax's BatchCreateJob. A required resource_type attribute causes the Hyrax ChildWorkJob to fail, but resource_type cannot be passed via attributes.
A required value of resource_type causes child works to not create.
PDF split is successful, and child works are created with resource types if the term applies.
<details>
</details>

Add resource type for child works

---

lib/iiif_print/version.rb

Update to version 3.0.2
