- app/actors/iiif_print/actors/iiif_print_upload_actor.rb
- app/jobs/iiif_print/create_pages_job.rb
- app/models/concerns/iiif_print/iiif_print_behavior.rb
- spec/actors/iiif_print/actors/iiif_print_upload_actor_spec.rb
- spec/factories/uploaded_txt_file.rb
- spec/models/concerns/iiif_print/iiif_print_behavior_spec.rb
Ref https://github.com/scientist-softserv/iiif_print/issues/7
- Refactor IiifPrintUploadActor
- Create IiifPrintBehavior module 
- Rename CreateIssuePagesJob to CreatePagesJob
- Passing specs for IiifPrintUploadActor & IiifPrintBehavior
> Refactor IIIF Print Upload Actor

- lib/tasks/set_child_works.rake
- lib/tasks/set_parent_thumbnail.rake
If a parent doesn't have a thumbnail, running this rake task will set its thumbnail to be its child's first file_set (currently ordered by source identifier, as that was the requirement set in LV). This may change later. 
This rake task was originally created as a backup fix, for when the SetParentThumbnailJob doesn't complete for whatever reason. 
command: `rake iiif_print:update:set_parent_thumbnail`
> [i30] - port over rake tasks from LV

- app/views/hyrax/file_sets/_actions.html.erb
When a user clicks to download a derivative, the file gets opened up in the browser which renders ridiculousness.  To download, a user would have to right click and save as.
The user can just click the download link and expect the file to download.
> add download attribute to download link

- app/helpers/hyrax/iiif_helper.rb
- app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
ref #28 
- this will bring in hyrax 3 version of the UV partial
ref #26
- the helper file doesn't appear to be generated by newspaper works gem but lives in [hyrax](https://github.com/samvera/hyrax/blob/main/app/helpers/hyrax/iiif_helper.rb) 
- it is referenced by the uv partial so i thought it would be a good idea to bring it over in this PR as well in case the application doesn't have those helper files
> add uv partial and its helper methods

- app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
- app/presenters/iiif_print/iiif_manifest_presenter_factory_behavior.rb
- lib/iiif_print/engine.rb
- spec/presenters/iiif_print/iiif_manifest_presenter_behavior_spec.rb
The [hyku](https://github.com/samvera/hyku/pull/1886) application will now detect if there is another implementation of `#search_search`.  If there is, it will use this one provided in the gem.
`Hyrax::IiifManifestPresenter::Factory#build` is now also decorated within the gem instead of in Hyku.
Currently the `#manifest_metadata` method is not fully implemented and because we're prepending `IiifPrint::IiifManifestPresenterBehavior`, it is now breaking the application, commenting it out for now
> I35 search service

- spec/spec_helper.rb
to remove tmp derivatives after each run
the internal test application's tmp derivatives folder would fill out with files that potentially conflicted with future tests and made them flaky
the tmp derivatives folder is cleared out after test suites are ran
> update spec helper

- spec/helpers/hyrax/iiif_helper_spec.rb
closes #28
This commit will bring over the `IiifHelper` spec from Hyrax 3.4.2.
> Add `IiifHelper` spec

- spec/presenters/iiif_print/iiif_manifest_presenter_factory_behavior_spec.rb
closes: #35 
This commit will add a spec for
`IiifPrint::IiifManifestPresenterFactoryBehavior#build`.
This PR is a continuation of #62
> Add a spec

- app/services/iiif_print/manifest_builder_service_behavior.rb
makes keyword arg optional to get past the following lint errors: 
The arguments are not being used because these methods have not been implemented yet.
> correct lint errors

- app/services/iiif_print/manifest_builder_service_behavior.rb
There is a weird interaction that happens when a child work gets added to the parent work.  When `#get_solr_docs` got called, it sometimes returned 1 `solr_doc` and when the #find happens, it sometimes returned nothing which resulted in `nil` being set as the image and passed along. This would cause issues further down and result in a failed manifest generation.  I took out `@presenter_solr_docs[presenter.id]` because it wasn't being used and seemed to be the source of the problem.
> Fix manifest bug

- app/presenters/iiif_print/work_show_presenter_decorator.rb
- app/views/hyrax/base/_representative_media.html.erb
- lib/iiif_print/engine.rb
ref #76 
This commit will bring over the `WorkShowPresenterDecorator` and the affected view partial from Louisville.  This decorator allows for the Universal Viewer to show up on a parent work that has a child work with a file set, but does not have its own file set.  Previously, the UV would not render.
Reference file:
https://github.com/scientist-softserv/louisville-hyku/blob/main/app/presenters/hyrax/work_show_presenter_decorator.rb
> [i76] - Make UV show up if parent has no file set

- config/routes.rb
- lib/generators/iiif_print/install_generator.rb
- spec/spec_helper.rb
This commit has two concerns:
- some cursory todo items (e.g. things I saw immediately when reading code).
- Removal of routes.
We didn't have engine routes, so I'm removing that file and the code that goes into supporting "tests" of routes.
> Removing reference to routes

- README.md
ref: #88 
Catalog seraching for child metadata and OCR was not working. This MR identifies the manual changes a dev would need to make to fix it. 
At a later date, we may discuss a way for the generator to implement this.
This work is dependent upon #81 
A Developer could test this locally. Otherwise, deploy hyku branch i87-ocr-search to hyku-iiif (ref testing instructions in #88 if you deploy) 
Create a new branch, based off of #81 (i81-uv-text-search)
Follow the instructions in the MR
1. Create a work. Upload an image that has text. OCR should run. Confirm that json coordinates are created as its derivatives. Confirm that a user can search for the text in the UV, and find a match.
2. Create a work. Attach a child. Confirm that a user can visit the parent's UV, search for the child's …
> [i88] - update readme instructions for enabling ocr catalog search

- lib/iiif_print/split_pdfs/pages_into_images_service.rb
Before this commit, the TIFF images that were being created had no compression on it resulting in extremely large files.  With this commit, we alter the Ghostscript command to add lzw or g4 compression to decrease the file size.
> Create reasonably sized tiffs

- app/services/iiif_print/pluggable_derivative_service.rb
- iiif_print.gemspec
- spec/services/iiif_print/pluggable_derivative_service_spec.rb
- spec/spec_helper.rb
- spec/support/iiif_print_models.rb
ea30d93c3d3878474a4cb1340b0145e9e5a30d90
68a565886051ccbc5da518eaa971c64172e05659
The primary purpose of this commit is to remediate the following code:
```ruby
def default_plugin_for(file_set)
if file_set.parent.try(:iiif_print_config?)
file_set.parent.iiif_print_config.derivative_service_plugins << default_plugin
else
[default_plugin]
end
end
```
As written, the above method was changing the configuration for a work's
parent.  Due to the implementation of the parent's `#iiif_print_config`
it was an isolated update (e.g. updating only the parent object's value
and not the parent object's class's value).
I found this bug by introducting random spec order.
With this commit, I'm doing a few things:
1. Reworking the `plugins_for` method; instead of updating the value, it
uses that value to …
> Further tidying of specs

- app/services/iiif_print/pluggable_derivative_service.rb
- lib/iiif_print/base_derivative_service.rb
- lib/iiif_print/jp2_derivative_service.rb
- lib/iiif_print/pdf_derivative_service.rb
- lib/iiif_print/text_formats_from_alto_service.rb
- lib/iiif_print/tiff_derivative_service.rb
- spec/support/iiif_print_models.rb
e1abf3edd59920b6038961459131bc7db5ab1525
Prior to this commit, we used an abbreviation for an undocumented
method.  To understand purpose, we need to read more about its
implementation.
With this commit, I'm renaming the method/constant to a more verbose
variable.  We have to read it more often than we will ever write it.
ac4cb0a2cfda49315216589d0539aac3d0fa4e50
Prior to this commit, we were using a constant and class method to
handle the configurability of the `target_extension`.
With this commit, we remove the constant and provide a class attribute
that allows for configuration and exposes an instance method.
Also, instead of using the terinary args test, I've added a positional
parameter with a default value.
> Reworking configuration options

- app/services/iiif_print/pluggable_derivative_service.rb
- spec/models/iiif_print/derivative_attachment_spec.rb
- spec/models/iiif_print/ingest_file_relation_spec.rb
e7e0675580cfbc3cbf6e472ca1e8354859d0e979
Prior to this commit, the `respond_to_missing?` method definition did
not have the correct method signature.  Which could cause failures
elsewhere.
Also, as much as we don't want to repeat knowledge regarding
implementation details, most references to method_missing and the
sibling respond_to_missing duplicate logic; in part to minimize
unnecessary calls.  (See [Always Define respond_to_missing?][1])
I renamed `name` to `method_name` to be consistent with the
parameters of the sibling methods.
And last, I made a change in the logic test to short-circuit faster and
not reference the file_set if we don't have "agreeable" parameters.
References:
- https://github.com/scientist-softserv/iiif_print/issues/43
[1]: …
> Refactoring specs to remove warning

- app/actors/iiif_print/actors/iiif_print_upload_actor.rb
- lib/iiif_print/configuration.rb
- lib/iiif_print/data/path_helper.rb
- spec/lib/iiif_print/data/work_derivatives_spec.rb
- spec/lib/iiif_print/data/work_files_spec.rb
- spec/misc_shared.rb
This commit changes the code to remove the following deprecation warnings:
```shell
DEPRECATION WARNING: You are using deprecated behavior which will be
removed from the next major or minor release. (called from
default_admin_set at
/app/samvera/hyrax-webapp/app/actors/iiif_print/actors/iiif_print_upload_actor.rb:91
```
```shell
DEPRECATION WARNING: Samvera is deprecating
Hyrax::Configuration#whitelisted_ingest_dirs in Hyrax 3.0. Instead use
Hyrax::Configuration#registered_ingest_dirs.
```
Further, it renames whitelist variables to registered, to echo the upstream `Hyrax::Configuration#whitelisted_ingest_dirs` deprecation advice.
> Removing deprecation warnings and renaming variable

- spec/services/iiif_print/pluggable_derivative_service_spec.rb
- spec/support/iiif_print_models.rb
Prior to this commit, the `FakeDerivativeService` leveraged a class instance variable.  This is a precarious implementation as we don't reset the variable in-between runs.
With this commit, we're shifting this "spy" class to be an instance of the class (thus the tracking values are isolated to each spec run).  We do this by having the "spy" conform to the interface of a plugin.
Related to:
-  https://github.com/scientist-softserv/iiif_print/issues/43
> Favoring instance over class for specs

- app/services/iiif_print/pluggable_derivative_service.rb
- lib/iiif_print/jobs/application_job.rb
- lib/iiif_print/jobs/create_relationships_job.rb
e8355e3c0a5e6e98225f31144c383949fef0ab8b
945472551e18a28787bea23cb41283289fcf725d
It is almost always better to reduce method chaining (e.g. `a.b.c.d`
moves to `a.d`).  See the [Law of Demeter][1], or the "Principle of
Least Knowledge."
In other words, I can know my neighbor, but I don't know (as well) my
neighbor's neighbor.
This refactor is made possible by introducing a [class_attribute][2] for
`target_extension`.
[1]: https://en.wikipedia.org/wiki/Law_of_Demeter
[2]: https://api.rubyonrails.org/classes/Class.html#method-i-class_attribute
8128923aa71eb4efc22b7abf17223a0b95f58eff
Prior to this commit, some of the methods were public when they need
not, nor probably should've been.  (Directly calling method_missing is
an anti-pattern).
With this commit, I'm moving methods to a private …
> Low-stakes refactoring with todo items

- app/renderers/hyrax/renderers/faceted_attribute_renderer_decorator.rb
- lib/generators/iiif_print/install_generator.rb
- lib/iiif_print/engine.rb
Prior to this commit, we were generating this decorator into the downstream application.  Thus this engine cedes control to the downstream application.
However, based on discussions, the `is_child_bsi` may not be in all implementations.  Which would mean we want this decoration to be configurable.
With this commit, we favor keeping the decorator inside the engine thus allowing for future configurability.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/40
> Moving generated file into engine app

- lib/iiif_print/data/fileset_helper.rb
- lib/iiif_print/data/work_derivatives.rb
- lib/iiif_print/data/work_files.rb
- spec/iiif_print/data/work_derivatives_spec.rb
- spec/iiif_print/data/work_file_spec.rb
- spec/iiif_print/data/work_files_spec.rb
- spec/misc_shared.rb
- spec/services/iiif_print/pluggable_derivative_service_spec.rb
- spec/services/iiif_print/text_formats_from_alto_service_spec.rb
This commit includes three concepts:
- Shifting from `class ==` to `is_a?` comparison
- Favoring `detect` over `find`
- Removing `xit` for some methods
The `is_a?` comparison allows for inheritance checks.
The `detect` over `find` is because in some of our test models we set
`#members` as an Array and in other work's members are
reflections (e.g. `has_many :members`) from `ActiveFedora::Base`.
Below is the keying error for the problem:
```shell
Failure/Error: first_fileset = work.members.find { |m| m.class == FileSet }
RuntimeError:
Couldn't find reflection
```
Removing `xit` follows on the work for favoring `detect`
> Favoring `is_a?` over `class ==`

- lib/iiif_print/data/work_files.rb
- spec/iiif_print/data/work_files_spec.rb
- spec/services/iiif_print/text_formats_from_alto_service_spec.rb
There are three things in this change:
1. Putting parentheses around a method call; the parser was confused by this.
2. Casting a reflection into an array (sometimes these are arrays sometimes reflections);  must be related to randomized specs.
3. Removing a trailing `)` that was causing a parse error.
> Removing parser ambiguity

- spec/iiif_print/catalog_search_builder_spec.rb
- spec/spec_helper.rb
de329cee9d24561204e4eafe4a855551e1254694
During a refactoring, I failed to move the spec to the right directory.
847a26d29afd4c0cc143aee879080c3a4c0b119e
Prior to this commit, we leveraged Hyrax's default noid minting
approach.  It appears that that changed from file based state tracking
to database state tracking.
This created a problem when rebuilding the internal application.  Namely
I encountered the following exception:
```
ActiveRecord::StatementInvalid:
Could not find table 'minter_states'
```
The option was to either:
1. run the noids-rails generator for the migrations as part of the
engine cart/install process...
2. set the noids minter class to be the file system.
I have chosen the latter; it's not something I'd want to do for
production but for tests, I'd rather not run another …
> Fixing broken spec

- README.md
Remove reference to "page" worktype
Add note about PDF splitting
> Adjust "Ingesting Content" section

- lib/iiif_print/engine.rb
With this commit, if the downstream application has Bulkrax we strongly encourage the Bulkrax version upgrade; though do provide a means of avoiding our strong recommendation.
> Adding version enforcement for Bulkrax

- README.md
Add instructions to enable IiifPrint::CatalogSearchBuilder. 
This is needed to return parents only, when searching the catalog controller.
> update readme to enable iiifprint catalog search builder

- lib/generators/iiif_print/install_generator.rb
Blacklight IIIF Search generator has some linting that does not agree with CircleCI on Hyku.  These two linting methods should address that so out of the box, IIIF Print installs should be lint free.
https://user-images.githubusercontent.com/19597776/221325592-9329a8cf-2f78-45c9-a593-bc1815ce57b5.mp4
> Add linting to generator

- lib/iiif_print/engine.rb
On hyku, a load issue was discovered once iiif_print was installed which caused missing translations. 
We traced it back to this decorate statement and moved it into an after_initialized block. After doing so, the local files were correctly listed in the I8n.load_path, as expected.
> move decorate statement into after inititalize block

- app/indexers/concerns/iiif_print/child_indexer.rb
the ADL pipeline issue traced back to the changes of this PR. 
The switch statement may not even be necessary because as implemented, it only applies to 1 account. What about the others? 
Removing it for now and with the assumption that it will apply to all work types by default( -> I'll test this on Adventist) 
For allinson flex apps we may need to bring it back but it will need to loop through all of the accounts, not just grab the first one.
> removing because as stated it only applies to the first account

- app/services/iiif_print/pluggable_derivative_service.rb
- lib/iiif_print/base_derivative_service.rb
- lib/iiif_print/configuration.rb
- lib/iiif_print/text_extraction/page_ocr.rb
- spec/iiif_print/base_derivative_service_spec.rb
- spec/iiif_print/configuration_spec.rb
- spec/iiif_print/jobs/child_works_from_pdf_job_spec.rb
- spec/iiif_print/jobs/create_relationships_job_spec.rb
- spec/indexers/concerns/iiif_print/indexes_full_text_spec.rb
- spec/services/iiif_print/pluggable_derivative_service_spec.rb
3f557f7b260202d9115584ba677219470073afc9
There were a few failing specs around constants not existing.  This
commit addreses those failures.
06bdcf9db23ea853a58b7b01a1ba7ebb6a30fddf
Prior to this commit, we were twice checking a file set's parent.  First
in the `Bulkrax::PluggableDerivativeService#plugins_for` methdod and
then immediately in the `Bulkrax::BaseDerivativeService.rb`.
With this commit, we're not repeating that logic.  Instead we're using
the plugins_for method to determine what are the possible valid plugins
for the file_set's parent.  And then we want to again answer what
derivative service is valid for the file set.
32c01d9197aacde0f9d425b58c2df0f77b54322e
Prior to this commit, we had a fully hard-coded tesseract command
invocation.
With this commit, we can provide …
> Enabling greater tesseract configurability

- README.md
- lib/generators/iiif_print/install_generator.rb
The [`BlacklightIiifSearch::InstallGenerator`][1] allows for skipping installing the SOLR changes.  See below:
```ruby
def add_solr_config
generate 'blacklight_iiif_search:solr' unless options[:'skip-solr']
end
```
With this commit, we'll skip over those changes.  The application will still have the the suggest routes and configuration; which may need further investigation: Is the Universal Viewer making requests that are silently failing?  Do we need the catalog controller configuration?
This all is very challenging to test without a full install.
The attached file (excluding the `vendor/plugins`) shows what changes will be made to British Library when we run an install using this change:
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/147
[1]: …
> Skip blacklight_iiif_search:install solr changes

- lib/iiif_print.rb
- lib/iiif_print/split_pdfs/base_splitter.rb
- lib/iiif_print/split_pdfs/pages_to_pngs_splitter.rb
- lib/iiif_print/split_pdfs/pages_to_tiffs_splitter.rb
- spec/iiif_print/split_pdfs/pages_to_pngs_splitter_spec.rb
- spec/iiif_print/split_pdfs/pages_to_tiffs_splitter_spec.rb
- spec/iiif_print_spec.rb
711583652618e7ec7df8714114f4f23ca5ccdda1
_Note: this commit assumes that we've merged #169._
It does the following things:
1. Extracts a `BaseSplitter` class
2. Creates a `PagesToTiffsSplitter`
3. Creates a `PagesToPngsSplitter`
4. Renames the default configured splitter class to preserve past behavior.
This will allow us to then configure which splitter we use:
1. Favor TIFFs when you want deeper zooms
2. Favor PNGs when you want to minimize storage space
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/293
- https://github.com/scientist-softserv/iiif_print/pull/169
74d9be415d01556c754ffef99b9bdb5338691c0c
Prior to this commit, we were always using a compression algorithm; even
when that algorithm did not apply to PNG.
With this commit, we conditionally apply a …
> Adding Pages to PNGs splitter

- lib/iiif_print/jobs/child_works_from_pdf_job.rb
- spec/iiif_print/jobs/child_works_from_pdf_job_spec.rb
ref: #167 
This commit will add zeros to Pdf and Page sequences so it correctly sorts as a string.  Added a xit spec as a placeholder for now.
NOTE: this screen shot is to show the padding, it is out of order because that is just how Hyrax displays it here.
> Add padding with zeros

- lib/iiif_print/split_pdfs/base_splitter.rb
- lib/iiif_print/text_extraction/page_ocr.rb
A few minor bugs were introduced during the refactor to clean up and clarify the PDF splitter in preparation for supporting splitting into PNG files. Originated in https://github.com/scientist-softserv/iiif_print/pull/169
Tesseract command was failing because "hocr" needs to come at the end of the tesseract command. Originated in  https://github.com/scientist-softserv/iiif_print/pull/156
> Bug fixes due to refactoring

- spec/test_app_templates/lib/generators/test_app_generator.rb
In testing, bundle was throwing an error and this seems to fix the problem.  Looks like the Redis gem updated on Feb 10th, 2023.
ref: https://github.com/redis/redis-rb/commit/e4f5299aa0109d1334564f20ae8522866ef554e9
> Update Redis gem

- app/presenters/iiif_print/work_show_presenter_decorator.rb
This is just a quality of life refactor.  In Essi, when changing any code that has to do with the `WorkShowPresenter` or `SolrDocument`, it for some reason looses the `#file_set_ids` method.  However, if you bracket notate it, it's fine.
> Refactor `#file_set_ids`

- lib/iiif_print/split_pdfs/base_splitter.rb
- lib/iiif_print/split_pdfs/pages_to_jpgs_splitter.rb
- spec/iiif_print/base_derivative_service_spec.rb
- spec/iiif_print/split_pdfs/base_splitter_spec.rb
- spec/iiif_print/split_pdfs/pages_to_jpgs_splitter_spec.rb
When I did some testing in, the PNG files are sometimes even too big. An example would be a 7.1MB PDF creates a 91MB TIFF or 52MB PNG.  This is a big reduction however we can do better.  Without losing noticeable quality, we can generate a 3.8MB JPG.
191472275ff6cce0c224a0d76bb23b22bf60efad
When I did some testing in, the PNG files are sometimes even too big. An
example would be a 7.1MB PDF creates a 91MB TIFF or 52MB PNG.  This is a
big reduction however we can do better.  Without losing noticeable
quality, we can generate a 3.8MB JPG.
9bc8adcbf24d9969e068be186339deeb2eea2b1c
Given that we change the compression during the calculation, we cannot
rely on the `self.class.compression` as the correct answer for the
`compression` property.
Instead, we should rely on the instance method (which …
> Add jpg splitter and fix a bug

- lib/iiif_print.rb
- spec/iiif_print_spec.rb
- spec/services/iiif_print/pluggable_derivative_service_spec.rb
Prior to this commit, we were generating several derivatives from the original file.
In conversations with clients, these extra derivatives are often confusing and represent additional processing and storage.  The use cases made more sense for things such as newspapers; in part to normalize the inputs.
The options are still available, but not as part of the default configuration.
With this commit, we reduce the default derivatives we run to a small set.
> Narrowing list of default service plugins

- app/presenters/iiif_print/work_show_presenter_decorator.rb
Ref: https://github.com/scientist-softserv/britishlibrary/issues/303
The prior implementation processed parent and child works separately to determine when to show the iiif_viewer.
However the child works option was incorrect, as it only looked for file_set_ids but didn't check file type or
permission.
This refactor fixes that issue in the most efficient way possible, and also splits out a method which can be overridden to allow for additional file type checks when used in combination with IiifAv gem (and can ultimately be refactored into a config variable).
> Fix work show presenter

- app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
- app/services/iiif_print/manifest_builder_service_behavior.rb
- lib/iiif_print.rb
[Add collection metadata to Allinson Flex](https://github.com/scientist-softserv/iiif_print/commit/2f96b5a810003045251d07e7c0aefd5267e64c29) 
Assuming Allinson Flex does not implement a property called 'collection'
to return the work's collection, this commit will inject the property so
it is available to be viewed in the metadata pane.  This will be in
parity with non-Allinson Flex applications.
---
[Add metadata to the parent](https://github.com/scientist-softserv/iiif_print/commit/b07dff66569bd243e8bb2f163edbee69210ed866) 
Previously, the metadata would always sit on the child canvas.  This
would fail to render any metadata for the parent work.  This commit will
fix that.
> Metadata pain

- app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
In Hyrax 3x, the sequence_rendering was sending a `[nil]` to the IIIF Manifest gem.  This override patches that.
> Add override for Hyrax

- README.md
- lib/iiif_print/engine.rb
- lib/iiif_print/homepage_search_builder.rb
ref https://github.com/scientist-softserv/iiif_print/issues/187
Recent works on the home page should not include child works. 
This implements a homepage search builder for iiif_print which adds `:show_parents_only` to the processor chain.
<details>
<summary>
Screenshot:
</summary>
</details>
> I 187 search recent works

- lib/iiif_print.rb
- lib/iiif_print/metadata.rb
- spec/iiif_print/metadata_spec.rb
This commit will remove empty strings from showing in the metadata pane. This occurs in a Bulkrax import when the header exists but there isn't a value.  Bulkrax would then map that property to `""`.  This would then show up in the metadata pane as just a label since the value is blank. Also in the commit, cleaned up some specs and removed `_work` from the `.default_fields` and `.fields_for_allinson_flex` because it was messing up the testing.
Before:
After:
> Remove empty strings from metadata pane

- lib/iiif_print/jobs/child_works_from_pdf_job.rb
Titles were padded to cause child works to show sequentially in the universal viewer. However, the ordered members being added were not padded to cause the same sequencing. This commit also pads the pdf & page numbers being used to order the child works so they will be sequenced correctly.
Ref https://github.com/scientist-softserv/britishlibrary/issues/339 as pages > 10 were previously out of sequence on the work show page.
<details>
<summary>Before & After Screenshots</summary
**Before:**
**After:**
</details>
> Sequence child works by pdf & page

- README.md
- app/services/iiif_print/manifest_builder_service_behavior.rb
- lib/generators/iiif_print/templates/config/initializers/iiif_print.rb
- lib/iiif_print/configuration.rb
- spec/iiif_print/configuration_spec.rb
Now that ordered members are sorted in order, the custom sort is no longer needed.  UV sorting will also follow ordered member sorting so the items partial and the UV will always be in sync.
ref: https://github.com/scientist-softserv/iiif_print/commit/e3384284a9992df867b7bedc256c82485355551d
> Remove canvas sorting

- README.md
- app/indexers/concerns/iiif_print/file_set_indexer.rb
- app/models/concerns/iiif_print/solr/document.rb
- app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
- lib/iiif_print/engine.rb
- spec/presenters/iiif_print/iiif_manifest_presenter_behavior_spec.rb
ref: https://github.com/scientist-softserv/britishlibrary/issues/335
This PR allows iiif_print to support iiif external image servers
There's a loading issue in dev; when we change code the app no longer hits our iiif_manifest_presenter_behavior.rb it reverts back to using the app instead of cloudfront. This seems to only impact dev but it's really annoying. 
We also added the DisplayImagePresenterBehavior prepend in the after_intitialize because the app couldn't find the digest method otherwise.
We will also need to figure out how to make serverless iiif work for audio/video files.
> [i335] - port over serverless code from nnp

- lib/iiif_print/text_extraction/page_ocr.rb
ref: #203 
Taking a page out of IU's book, they prepend `OMP_THREAD_LIMIT=1` to their tesseract calls.  This would improve performance in a multithreaded deployed environment.
ref: https://github.com/IU-Libraries-Joint-Development/essi/blob/a8a48da218e1084b13d250edf287eb6d1811d92c/app/services/processors/ocr.rb#L14
> Add `OMP_THREAD_LIMIT=1` to tesseract call

- lib/iiif_print/configuration.rb
- lib/iiif_print/lineage_service.rb
- spec/iiif_print/configuration_spec.rb
Prior to this commit, we assumed that a work's `id` was the mechanism for always identifying a work in regards to it's ancestry/lineage.
However, for implmentations that incorproate slug behavior, that reality is not always the case.
With this commit, we expose a configurable mechanism for altering the ancestry functionality.
Related to:
- https://github.com/scientist-softserv/adventist-dl/pull/354/
- https://github.com/scientist-softserv/adventist-dl/issues/319
> Extracting ancestry identifier configurability

- lib/iiif_print/image_tool.rb
The `identify -verbose` was too expensive of a method because it is getting back a ton of information that wasn't even being used.  We are opting for `identify -format` to pull only the information we are looking to use instead to help speed up the `CreateDerivativesJob` process.
The output looks something like:
```sh
Geometry: 5100x6592
Depth: 8
Colorspace: sRGB
Alpha: Undefined
MIME Type: JPEG
```
> Optimize identify -verbose

- lib/iiif_print/configuration.rb
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
- lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
- spec/iiif_print/configuration_spec.rb
0d88a021ae038a27996bfd4cbc6c8f623a4aac91
Prior to this commit, we had a hard-coding approach to configuring a
child work's title.
With this commit, we preserve the existing behavior (for better or
worse) but expose a configuration option to help in the process
generation.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/204
e83f70a5ea0064bcb4a07bdc81d2693397dba775
ac0b5edfb7fa21b234f067ad796a0eab4e1bed67
Based on feedback from clients and process improvements, this is a
change that will help ensure more unique titles; and make a visiual
connection to the PDF that child works were generated from.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/204
d435eeb0622a46364eb48d0a7add8a1e0517f1ea
This commit includes a deprecation documentation, a bit of …
> Adding child_file_title_generator_function

- lib/iiif_print/jobs/create_relationships_job.rb
Some jobs are running and doing nothing, and this results in the PendingRelationships table getting emptied. The goal is to capture a job error and make this recoverable because we still have the data for relationships.
> Raise an error on relationships job failure

- app/services/iiif_print/manifest_builder_service_behavior.rb
This is an edge case, but prevents a manifest failure. Previously we got an error because of calling `IiifPrint.manifest_metadata_from(work: image, presenter: presenter)` when image was nil.
<details>
<summary> Before & After Screenshots</summary>
**Before:**
**After:**
</details>
1. Add a new work with an image file.
2. When viewing the above work, add a child work as a child using the `Attach Child` dropdown option. Use a PDF file for this child's file.
3. When returning to the original work, universal viewer should show both the original image and all of the child work's split child work images.
> Add guard to method

- app/indexers/concerns/iiif_print/child_indexer.rb
- lib/iiif_print/lineage_service.rb
- spec/iiif_print/lineage_service_spec.rb
Prior to this commit, we had a method that returned unexpected values, in part because upstream behaves unexpected.
Due to a long-standing hack in Hyrax, the file_set_ids_ssim contains both file_set_ids and child work ids.
The Hydara::Works implementation of file_set_ids is `members.select(&:file_set?).map(&:id)`; so no sense doing `object.file_set_ids + object.member_ids`
See
https://github.com/samvera/hyrax/blob/2b807fe101176d594129ef8a8fe466d3d03a372b/app/indexers/hyrax/work_indexer.rb#L15-L18
With this commit, we're both simplifying the logic, and clarifying the behavior by renaming the method (and preserving the existing method name for those who like obfuscation).
> Renaming method for clarity for a confusing reality

- README.md
- app/helpers/iiif_print/iiif_helper_decorator.rb
- app/models/concerns/iiif_print/solr/document.rb
- app/models/iiif_print/iiif_search_response_decorator.rb
- app/search_builders/concerns/iiif_print/highlight_search_params.rb
- app/views/catalog/_index_header_list_default.html.erb
- app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
- lib/iiif_print/configuration.rb
- lib/iiif_print/engine.rb
- spec/iiif_print/catalog_search_builder_spec.rb
ref: #183
[Add a highlight detection](https://github.com/scientist-softserv/iiif_print/commit/172e13014679ef6f8806e58a69922f96192da49f) 
The `#has_any_highlighting?` method is used to determine if the search
returned any highlighting. If it did, then we add the parent_query to
the search params so that the search results.  This will avoid causing
and No matches found notification in the UV search.  Also in this
commit, we change `hl.fl` to return all fields that are indexed.
---
[Add IIIF Helpers into the load path](https://github.com/scientist-softserv/iiif_print/commit/1250144d026fd58ede24c60456a2808ee25dce13) 
This commit makes the IIIF Helpers work by loading in the engine.rb.
The main reason for the change is the get the #uv_search_param method
usable for the Universal Viewer.  This …
> Catalog to uv search

- lib/iiif_print/configuration.rb
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
- spec/iiif_print/configuration_spec.rb
This commit adds a configuration option for the attributes that are copied from the parent work to the child work. This can allow the child attributes to be more customizable if different projects want different attributes for their child works other what we prescribe.
> Add configuration for child work attributes

- lib/iiif_print/split_pdfs/pdf_image_extraction_service.rb
PDF splitting was locking up during splitting command.
Refs https://github.com/scientist-softserv/britishlibrary/issues/385
IiifPrint::Jobs::ChildWorksFromPdfJob hung in sidekiq and had to be cancelled. The file did not get split.
File now splits correctly but universal viewer breaks due to solr query too large. [This is a new bug ticket.](https://github.com/scientist-softserv/iiif_print/issues/224)
<details>
</details>
> Omit syntax warnings from command

- app/models/iiif_print/iiif_search_response_decorator.rb
reverts prior change because it causes a bug where the no matches found msg is never returned
We implemented this change (in [592537](https://github.com/scientist-softserv/iiif_print/commit/592537f13841f0c6f549f40495d09078cb498127)) as a way to solve: i24 - [Searching for parent metadata leads to error](https://github.com/scientist-softserv/essi/issues/24)
However, it introduced a new bug where now the no matches msg ever displays, even when there aren't any matches.
If there are no matches from a UV search, a no matches found popup should appear
> revert change that introduced no matches found bug

- app/services/iiif_print/manifest_builder_service_behavior.rb
- lib/iiif_print/configuration.rb
- spec/iiif_print/configuration_spec.rb
As a user, I want to see the UV display the different works in filename order.
Refs https://github.com/scientist-softserv/essi/issues/11
Canvas sort by ordered members no matter what
Canvas sort by ordered members by default but can be configured to be sorted by work properties or canvas label.
[Add back canvas sorting with a configuration](https://github.com/scientist-softserv/iiif_print/commit/e4d197d11d0d38d1573d21f17deb10f7ad818077) 
This commit will bring back a previously deprecated feature of sorting
the canvas.  This time, the canvas will only be sorted if the
configuration is set to do so.  The default is to not sort the canvas
and instead follow the order_members of the work.
---
[Add sort by canvas label](https://github.com/scientist-softserv/iiif_print/commit/febc3a033ecce8ffe9 …
> Sort canvas configuration

- app/indexers/concerns/iiif_print/child_indexer.rb
Set conditional to verify GeneratedResourceSchema is defined.
Refs 
https://github.com/orgs/scientist-softserv/projects/43?pane=issue&itemId=25971227
After creating a new work type, a developer could not run the pending migrations due to work_type::GeneratedResourceSchema being undefined. 
The condition statement added to the code verifies the constant "work_type::GeneratedResourceSchema" is defined. If defined, the code will execute.
> Update GeneratedResourceSchema in childed_indexer

- app/models/concerns/iiif_print/solr/document.rb
- app/presenters/iiif_print/iiif_manifest_presenter_behavior.rb
- lib/iiif_print.rb
- lib/iiif_print/configuration.rb
- lib/iiif_print/metadata.rb
- spec/iiif_print/configuration_spec.rb
- spec/iiif_print_spec.rb
[Filter out admin_only fields](https://github.com/scientist-softserv/iiif_print/commit/6b854e3379cfb960882efca1a0f2445e00de2779) 
This commit will filter out metadata fields that are meant to be admin
only from displaying in the UV.  This is done by adding a reject if the
Allinson Flex profile indicates that this field is `admin_only`.
---
[Make QA work for allinson_flex](https://github.com/scientist-softserv/iiif_print/commit/ce4074ed060c717e687ff757176343d955d82a38) 
Allinson Flex profiles don't have an option other than indicating which
fields to be facetable.  This commit will make QA work for Allinson Flex
by assuming the field names "rights_statement" and "license" will be QA
fields.
---
[Add a way to sort Allinson Flex metadata](https://github.com/scientist-softserv/iiif_print/commi …
> Updating allinson flex features

- app/services/iiif_print/manifest_builder_service_behavior.rb
- iiif_print.gemspec
Prior to this commit, the metadata for the parent image would display both on the manifest and canvas levels. In this commit, we check if the image we are looking at is on the parent or the child.  If it is on the parent, we won't display it on the canvas level because it is already being displayed on the manifest level.
Before:
After:
> Don't show child metadata on the parent image

- app/models/iiif_print/iiif_search_decorator.rb
- lib/iiif_print/engine.rb
- spec/models/iiif_print/iiif_search_decorator_spec.rb
ref: https://github.com/scientist-softserv/essi/issues/23, https://github.com/scientist-softserv/essi/issues/24
This commit will override `BlacklightIiifSearch::IiifSearch#solr_params` to include the parent metadata fields in a UV search.
> Search parent metadata instead of no match found

- lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
- spec/iiif_print/blacklight_iiif_search/annotation_decorator_spec.rb
This commit removes additional search terms from the query string that were being added through the IiifPrint::IiifSearchDecorator#solr_params override.
> Remove additional search terms from query string

- app/indexers/concerns/iiif_print/child_indexer.rb
- lib/iiif_print/configuration.rb
This PR is to address the feedback from the following ticket. The user was still able to see the child works in the catalog and recent works section. To resolve this, we are setting the child work is_child attribute to be true on default. 
Refs https://github.com/scientist-softserv/britishlibrary/issues/387
ref: https://github.com/scientist-softserv/britishlibrary/issues/387#issuecomment-1542771258
As a result, you cannot see the child records while it's still processing. The user should and does not see child works in the following scenarios: 
Notice is_child property is being set to true in the CreateWorkJob: 
sample work: [service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf](https://github.com/scientist-softserv/iiif_print/files/11456897/service-rbc-rbc0001-2015-2015gen56010-2015gen5 …
> [i387] - add default value to is_child property

- app/services/iiif_print/pluggable_derivative_service.rb
[🐛 Fix a NilClass error](https://github.com/scientist-softserv/iiif_print/commit/445f6cc7ec1e7376860a33f0a95f2c4abee57ae9) 
This will fix a bug in Adventist when a work couldn't be deleted.
> 🐛 Fix a `NilClass` error

- lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
- spec/iiif_print/blacklight_iiif_search/annotation_decorator_spec.rb
This commit will fix the removal of the additional query terms.  Here we use a regular expression to remove the additional query terms from the query string instead of using the `gsub` method.  This is more accurate because it was noticed that `document['is_page_of_ssim']` isn't always what we expect.  It does not work in a nested work context.
> 🐛 Fix additional query terms removal

- .rubocop.yml
- lib/iiif_print.rb
- lib/iiif_print/engine.rb
- lib/iiif_print/jobs/create_relationships_job.rb
- spec/iiif_print/jobs/create_relationships_job_spec.rb
Some works are losing child relationships when more than one PDF is attached to the work. This may happen due to a race condition between the child works being attached to the parent after splitting of the first PDF, and the ordered members being cleared in `Hyrax::Actors::OrderedMembersActor` while attaching the second PDF fileset to the work.
This change brings the CreateRelationshipsJob into alignment with the similar logic in Bulkrax's CreateRelationshipsJob, and adds record locking to the parent record to prevent race conditions from overwriting data.
Refs #233
Related to https://github.com/samvera-labs/bulkrax/issues/804
- Some works lose part or all of their child relationships.
- A parent work shows all of its child works.
- Pending relationships entries do not get removed if all …
> Rework relationships job

- iiif_print.gemspec
Why change `< 4.0` to `< 4`?  I was encountering issues where bundler was setting the dependency to `hyrax v4.0.0.rc3`.  This change remedied that.
Why remove `~> 3.1` from `rspec-rails` dependency?  I was getting issues with what version of Rails was required.  By removing this hard dependency, we're able to let these gems sort things out.
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/330
> ⚙️ Adding derivative-rodeo gem 🤠

- app/actors/iiif_print/actors/file_set_actor_decorator.rb
- lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
As I work on the Derivative Rodeo handling of PDFs, consolidating the logic to be within the refactored service.  This allows for more easily checking the Derivative Rodeo for a corresponding PDF that has already been pre-processed.
This is a significant refactor in that I want a keen eye reviewing the changes to ensure I haven't introduced a logic bug in the transformation.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/219
> ♻️ Moving PDF file split guards into the service

- iiif_print.gemspec
This commit removes `reform-rails v0.2.3` as a hard dependency because v0.2.5 fixed the problem that caused Hyrax not to build.
- See https://github.com/trailblazer/reform-rails/issues/99
> ⚙️ Remove `reform-rails` dependency

- app/services/iiif_print/pluggable_derivative_service.rb
- lib/iiif_print.rb
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
- lib/iiif_print/split_pdfs/base_splitter.rb
- lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
- spec/iiif_print/split_pdfs/base_splitter_spec.rb
This commit is a refactor in-place.  The primary goal is to allow for passing the file_set to the child works; something that is ideal for the derivative rodeo's interface.
This is intended to be a swap-in-place change.  That is to say, if we deploy this change and have already enqueued jobs, nothing will fail nor break.  The past enqueued jobs (with a work) will use the work based logic but future enqueueings will use file_set.
In using the file_set, we also avoid the issue of having passing a `nil` as the parent, and thus creating an infinite rescheduling cycle.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/220
Refs #issuenumber
<details>
</details>
> ♻️ Preparing Splitter Service Swap for DerivativeRodeo

- app/services/iiif_print/derivative_rodeo_service.rb
- app/services/iiif_print/pluggable_derivative_service.rb
- docker-compose.yml
- iiif_print.gemspec
- lib/iiif_print.rb
- lib/iiif_print/data/fileset_helper.rb
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
- lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
- spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
- spec/services/iiif_print/derivative_rodeo_service_spec.rb
c6be86fb3e5d6c737317336f168607048c35d1ce
Add a new PDF splitter option that wraps the DerivateRodeo's
PdfSplitGenerator.  It handles, in theory, PDF splitting and the
derivative's generated in the DerivativeRodeo.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/220
Co-authored-by: LaRita Robinson <larita@scientist.com>
Co-authored-by: Shana Moore <shana@scientist.com>
> 🎁 Add derivative_rodeo_splitter

- lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
- spec/factories/newspaper_page_solr_document.rb
- spec/iiif_print/blacklight_iiif_search/annotation_decorator_spec.rb
This commit will add assurance that we are getting the FileSet id and not some other work type id.
> 🐛 Ensure `FileSet` id

- app/helpers/iiif_print/iiif_print_helper_behavior.rb
- app/helpers/iiif_print_helper.rb
- lib/generators/iiif_print/install_generator.rb
- lib/generators/iiif_print/templates/helpers/iiif_print_helper.rb
Refs: https://github.com/scientist-softserv/adventist-dl/issues/469
Method `render_ocr_snippets` was causing AbstractController::DoubleRenderError
() during random situations, due to including the IiifPrintHelper in
ApplicationController.
This pull request moves it into a helper module which is injected by the
install generator, [which matches how it was done in LV](https://github.com/scientist-softserv/louisville-hyku/blob/b672d2a3213aaee84c082eb8083d8ad70733036b/app/helpers/newspaper_works_helper.rb#L3) & NNP. 
The app randomly throws AbstractController::DoubleRenderError when viewing the catalog results page.
The catalog results page which was previously erroring resolves successfully.
<details>
</details>
> 🐛 I469 adv search then paginate

- app/actors/iiif_print/actors/file_set_actor_decorator.rb
- app/helpers/iiif_print/iiif_print_helper_behavior.rb
- app/helpers/iiif_print_helper.rb
- lib/generators/iiif_print/install_generator.rb
- lib/generators/iiif_print/templates/helpers/iiif_print_helper.rb
- lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
Derivative Rodeo refactoring broke PDF splitting. 
This pull request fixes PDF splitting, and brings in [subsequent changes from the no-rodeo branch](https://github.com/scientist-softserv/iiif_print/pull/255) to bring main back up to date.
Refs 
- https://github.com/scientist-softserv/iiif_print/pull/254 and https://github.com/scientist-softserv/adventist-dl/issues/469
- [Originating commit for bug](https://github.com/scientist-softserv/iiif_print/commit/5df1264d88149bb0f1eb0b7f78569e8e124690c0)
PDF splitting was getting ignored.
PDFs split into viewable child works.
<details>
</details>
Exceptions are being swallowed somewhere... the errors this bug caused should have been showing up in either worker logs or sentry, but they didn't.
> 🐛 Restore PDF splitting functionality to main and bring in subsequent code changes

- lib/iiif_print/text_extraction/hocr_reader.rb
- spec/iiif_print/text_extraction/hocr_reader_spec.rb
This commit is basically the IIIF Print version of https://github.com/scientist-softserv/derivative_rodeo/pull/34/commits which should fix the problem of having duplicated word coordinates.
Ref:
- https://github.com/scientist-softserv/adventist-dl/issues/477
Word search counts sometimes don't match because coordinates are being duplicated.
Word counts are sometimes off.
Word counts should be accurate.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> 🐛 Fix word count

- app/services/iiif_print/derivative_rodeo_service.rb
- iiif_print.gemspec
- lib/iiif_print.rb
- spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
- spec/services/iiif_print/derivative_rodeo_service_spec.rb
This commit leverages the conventions established in the DerivativeRodeo around where we're writing split pages and their derivatives.
The inline comments that are written/amended with this PR should be read closely for clarity and intention.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/251
- https://github.com/scientist-softserv/derivative_rodeo/pull/48
> 🎁 Add ability to find pages split from a PDF

- app/services/iiif_print/derivative_rodeo_service.rb
- lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
This commit contains four primary changes:
1. Fixing a misnamed constant.
2. Moving setting the optional filename to a point before we use the filename.
3. Leveraging if include instead of case statements
4. Adding exception decorating to provide additional context.
Of these, the quality of debugging change to exceptions pays the most dividends.  It's helped provide insight into the specific URI that's failing.
Related to:
- https://github.com/scientist-softserv/derivative_rodeo/issues/56
> 🐛 Fixing issue with misnamed constant and using variable before declared

- app/services/iiif_print/derivative_rodeo_service.rb
- lib/iiif_print.rb
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
This commit includes three substantive changes:
- Extracting a method for determining the directory in which to look for a file.
- Addressing a very odd bug found in `public_send` behavior.
- Adding a fallback when we don't have an ancestor.
First, the fallback.  It is hacky (as noted by the `HACK:` comment). But it's quick and for Adventist is suitable.  We could extract a function that is the fallback and then call that.
Second, the odd bug manifested as `nil` being raised as an exception; that is to say with the original `rescue => e` the `e` was `nil` (and it's class was `NilClass`).
I found that if I removed the
`IiifPrint.public_set(ancestor_method, file_set)` and made an explicit call, then the exception went away; albeit now returning `nil`.
Which leads to the `HACK:` for handling …
> 🐛 Adding more robust (albeit hacky) handling of ancestors

- app/views/hyrax/base/_representative_media.html.erb
This commit will modify the _representative_media partial to acknowledge the alt text of the image if it exists.
> 🎁 Make representative media alt text dynamic

- app/services/iiif_print/derivative_rodeo_service.rb
- iiif_print.gemspec
- lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
4a2944d61fb3373c5fd368898bae5c99af89bce2
This commit contains 3 separate concepts but they are all in service of
improved legibility:
1. Changing the hash to assume multi-line
2. Changing the return value to be a string instead of Array of Rodeo
Locations
3. Adding a bit of documentation
All of this is in service of helping triage what's going on.
Related to:
- https://github.com/scientist-softserv/derivative_rodeo/issues/56
6d17751b3ebf5e04cd631f392b75fb552aeffadb
This includes the various tweaks in the Rodeo to help improve debugging
and checking logs for behavior.
> 📚 Minor changes to improve legibility

- app/views/hyrax/base/_representative_media.html.erb
Prior to this commit, the logic brough by IIIF Print was:
```html
<% if presenter.iiif_viewer? %>
<% if defined?(viewer) && viewer %>
<%= iiif_viewer_display presenter %>
<% else %>
<%= render media_display_partial(presenter.representative_presenter), file_set: presenter.representative_presenter %>
<% end %>
<% else %>
<% alt = block_for(name: 'default_work_image_text') || 'Default work thumbnail' %>
<%= image_tag default_work_image, class: "canonical-image", alt: alt %>
<% end %>
```
We would check if we should use the IIIF viewer.  And because we'd disabled it for the tenant, the answer was no.  The fallback was to then render a default thumbnail.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/276
- https://github.com/scientist-softserv/palni-palci/issues/715
- …
> 🐛 Render thumbnails when IIIF Print disabled

- app/views/hyrax/file_sets/_actions.html.erb
- lib/iiif_print/data/work_derivatives.rb
This commit will remove the Fedora call from the view.  Instead of passing in the presenter id, we will pass in the presenter object.  This then doesn't make the WorkDerivative look for the first file_set which is where the Fedora call is.
Ref:
- https://github.com/scientist-softserv/iiif_print/issues/273
> 🐛 Fix calling Fedora from view

- iiif_print.gemspec
There doesn't look like anything that's Rails 5 dependent here.
> Loosen up rails restriction

- lib/iiif_print/errors.rb
- lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
- spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
Prior to this commit, if we did not actually have preprocessed file in
the remote system, we'd encounter errors with files missing; we assumed
we could "copy" the preprocessed url to the local file.
With this commit, we check to see if the preprocessed file exists.  Then
fallback to a specified FileSet#remote_url and the fallback even
further.
The specs define the expected behavior.
Closes #282
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/282
> 🎁 Add graceful fallback of preprocessing

- app/actors/iiif_print/actors/cleanup_file_sets_actor_decorator.rb
- app/actors/iiif_print/actors/file_set_actor_decorator.rb
- app/indexers/concerns/iiif_print/child_indexer.rb
- app/models/concerns/iiif_print/set_child_flag.rb
- app/models/concerns/iiif_print/solr/document.rb
- app/models/iiif_print/pending_relationship.rb
- db/migrate/20231110163052_add_model_details_to_iiif_print_pending_relationships.rb
- lib/iiif_print.rb
- lib/iiif_print/engine.rb
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
- lib/iiif_print/jobs/create_relationships_job.rb
- lib/iiif_print/split_pdfs/destroy_pdf_child_works_service.rb
- spec/iiif_print/jobs/create_relationships_job_spec.rb
- spec/iiif_print/split_pdfs/destroy_pdf_child_works_service_spec.rb
related to 
- https://github.com/scientist-softserv/adventist-dl/pull/656
* Add parent_model, child_model, and file_id to the iiif_print_pending_relationships table for easier queries.
The goal here is twofold:
1. Add file_id of the triggering PDF's fileset, to be able to tie pending relationships to a specific PDF file, rather than a work, as one work may have multiple PDF attachments begin split.
2. Add parent & child model, to have everything needed in the PendingRelationship table to rerun a relationship job which may have run out of retries
* Add service to destroy child works and pending relationships as a PDF fileset is destroyed.
Future enhancements could include: 
1. Submitting the service as a background job
2. Create a way to do the PDF splitting separate from an import, using …
> :gift: IiifPrint Enhancements to clean up split works as PDF fileset is deleted

- .solargraph.yml
- iiif_print.gemspec
I have used the following to get jump to definition and render
documentation for the symbol at cursor.
1.  Add solargraph as a development dependency
2.  Run `bundle`
3.  Run `bundle exec yard gems` (or target specific gems)
4.  Add "relevant" gems to the `.solargraph.yml`
The above should *not* be in the docker container.  You would run this
in the environment where your editor is running.  There is probably a
way to make that work with Docker, but I’m not here for that today.
> 🧹 Add Solargraph as dependency

- app/services/iiif_print/derivative_rodeo_service.rb
- lib/iiif_print/split_pdfs/base_splitter.rb
- lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
- spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
We need to address the case where SpaceStone failed to copy the file
into S3.  When the file does not exist in S3, we can check if we have
the file locally and use that as the pre-processed location.  Otherwise,
we can copy the original remote file and proceed.
Related to:
- https://github.com/scientist-softserv/iiif_print/pull/283
- https://github.com/scientist-softserv/iiif_print/issues/282
> 🐛 Leverage CopyGenerator to ensure we have local copy

- app/actors/iiif_print/actors/file_set_actor_decorator.rb
- lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
The incoming path has been using a temp file location which no longer exists when the ChildWorksFromPdfJob runs, so child works have not been created during the imports using derivative rodeo.
This change uses the fileset's actual file to trigger the child works creation behavior.
When a PDF is attached to a work, the child works are successfully created. 
PDF splitting is expected to complete normally, whether via a standard Bulkrax import, an import using files from SpaceStone, or a UI import.
Sample test via this OAI import: https://adl.s2.adventistdigitallibrary.org/importers/108?locale=e
> Create Child Works based on PDF fileset's file

- app/actors/iiif_print/actors/file_set_actor_decorator.rb
- spec/iiif_print/split_pdfs/derivative_rodeo_splitter_spec.rb
- spec/services/iiif_print/derivative_rodeo_service_spec.rb
Closes #291
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/291
> 🧹 Fix broken specs

- app/actors/iiif_print/actors/file_set_actor_decorator.rb
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
Even though the file is put into the correct path location during the child_work_creation_from_pdf_service, we sometimes were finding that the file did not exist at the point we needed it (when running larger import batches). This change:
- ensures the file exists at the path
- reports if no image_files are found to split into
<details>
</details>
> Report errors and ensure file exists

- lib/generators/iiif_print/install_generator.rb
Prior to this commit, the `helpers/iiif_print_helper.rb` file installed
in `Rails.root + /helpers/iiif_print_helper.rb`; it should be in
`app/helpers/iiif_print_helper.rb`
> 🐛 Fix install location for helpers/iiif_print_helper

- app/services/iiif_print/derivative_rodeo_service.rb
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
- lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
- lib/iiif_print/split_pdfs/destroy_pdf_child_works_service.rb
This commit replaces raising exceptions when we can't derive the URL. Instead it opts to return nil and let the caller determine what to do.
The primary result is that it's easier to have a rodeo configuration "miss" finding files in the pre-process location due to configuration issues.
But alas, that's the nature of a rodeo.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/294
> 🐛 Work through fallback of rodeo URLs

- README.md
- app/services/iiif_print/derivative_rodeo_service.rb
- lib/iiif_print/errors.rb
- lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb
Prior to this commit, IIIF Print assumed that every file of a given
mime-type would use all of the same generators.  However, that is not
necessarily the case.
With this commit:
- Updated documentation based on a read of the generated Yardoc
- Added `DerivativeRodeoService.named_derivatives_and_generators_filter`
- Added a `clone` of attributes
The clone is in place to help ensure that as we apply the filter we
don't accidentally delete the application's configuration for mime
category and expected derivatives.
For example, let's say I have the following nested hash:
```ruby
nested_hash = {
pdf: {
thumbnail: "DerivativeRodeo::Generators::ThumbnailGenerator"
},
image: {
thumbnail: "DerivativeRodeo::Generators::ThumbnailGenerator",
json: …
```
> 🎁 Introduce .named_derivatives_and_generators_filter

- app/indexers/concerns/iiif_print/child_indexer.rb
- app/models/concerns/iiif_print/solr/document.rb
As a `_tsi` it's tokenized and we can't use it reliably for join
queries.
As an `_ssi` the following Solr `q` value will allow me to query all
documents that have an `application/pdf` mime_type (e.g. a FileSet) and
do not have child works that were split from the given PDF.
```
mime_type_ssi:application/pdf AND
-_query_:"{!v='id:split_from_pdf_id_tsi'}"
```
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/681
> 🐛 Favor `_ssi` field over `_tsi` for split from PDF

- Gemfile.lock
- README.md
- lib/iiif_print.rb
- lib/iiif_print/configuration.rb
- lib/iiif_print/jobs/request_split_pdf_job.rb
- lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
- spec/iiif_print/configuration_spec.rb
- spec/iiif_print_spec.rb
Prior to this commit, we always split every PDF file.  And for some
situations, we do not want split a PDF (e.g. In Adventist when we have a
work that attaches a reader and archival PDF; we don't need/want to
split the reader PDF, as we're splitting the archival PDF).
> 🎁 Add config for skipping splitting by file suffix

- Gemfile.lock
- iiif_print.gemspec
- lib/iiif_print/jobs/child_works_from_pdf_job.rb
9c3713c70833c0ebdc6c08ae2fba9b497794243e
`File` does not respond to `.rm_f`; we instead want to use
`FileUtils.rm_f`.
Co-authored-by: Kirk Wang <k3wang@gmail.com>
61350ae797afb7c89c7c7a3302a4deabf6ad5593
Related to:
- https://github.com/scientist-softserv/utk-hyku/pull/575
- https://github.com/scientist-softserv/palni-palci/pull/918
> 🐛 Favor `FileUtils.rm_f`

- iiif_print.gemspec
There's no need to include the spec files in the gemfile list.  And including `bin/rails` can wreck havoc on the downstream application.
Related to:
- https://github.com/samvera/hyrax/pull/6146
> 🧹 Exclude specs and bin/rails from gem files

- README.md
- app/models/concerns/iiif_print/solr/document.rb
- app/services/iiif_print/manifest_builder_service_behavior.rb
- lib/iiif_print.rb
- lib/iiif_print/catalog_search_builder.rb
- lib/iiif_print/configuration.rb
- lib/iiif_print/engine.rb
- lib/iiif_print/homepage_search_builder.rb
- lib/iiif_print/persistence_layer.rb
- lib/iiif_print/persistence_layer/active_fedora_adapter.rb
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
- spec/iiif_print/configuration_spec.rb
- spec/spec_helper.rb
With Valkyrie looming large, this change refactors the code towards an
adapter pattern; one that will allow for creating a Valkyrie adapter and
then configuring IIIFPrint accordingly.
We'll also need to consider how we duplicate the actor work within a
transaction and/or publisher/listener setup.
There are likely other places where we're making assumptions about
presenters and/or the data models we're processing.
Related to:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/35
- https://github.com/scientist-softserv/iiif_print/issues/312
> ♻️ Extract direct ActiveFedora calls to adapter

- app/actors/iiif_print/actors/file_set_actor_decorator.rb
- app/transactions/hyrax/transactions/iiif_print_container_decorator.rb
- app/transactions/hyrax/transactions/steps/conditionally_destroy_children_from_split.rb
- lib/iiif_print.rb
- lib/iiif_print/data/work_derivatives.rb
- lib/iiif_print/engine.rb
- lib/iiif_print/persistence_layer.rb
- lib/iiif_print/persistence_layer/active_fedora_adapter.rb
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
- lib/iiif_print/split_pdfs/destroy_pdf_child_works_service.rb
- spec/transactions/hyrax/transactions/container_decorator_spec.rb
- spec/transactions/hyrax/transactions/iiif_print_container_decorator_spec.rb
- spec/transactions/hyrax/transactions/steps/conditionally_destroy_children_from_split_spec.rb
Valkyrie leverages transactions instead of the actor stack; as such we
need to mirror the actor stack behavior as a transaction (or listener).
In this case, we should use a transaction.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/312
> 🎁 Add Transaction for Cleaning Up Split Pages

- app/listeners/iiif_print/listener.rb
- lib/iiif_print/engine.rb
- spec/listeners/iiif_print/listener_spec.rb
Why a listener and not a transaction?  In part because the moment I want
to perform the conditional enqueuing is at the point where the
`Hyrax::WorkUploadsHandler` does it's job.  That is when we have:
- the parent work
- the file set
- the original file
- the user
The `Hyrax::WorkUploadsHandler` is most analogous to the behavior in
`Hyrax::Actors::FileSetActor#attach_to_work` and
`Hyrax::Actors::FileSetActor#create_content`.  Fortunately, Hyrax's
transaction and upload handler remove the conditional handling we needed
between uploading a remote file and directly uploading a file.
Related to:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/35
- https://github.com/scientist-softserv/hykuup_knapsack/issues/99
- https://github.com/scientist-softserv/iiif_print/issues/312
> 🎁 Add listener for handling file set attachment

- app/transactions/hyrax/transactions/iiif_print_container_decorator.rb
- app/transactions/hyrax/transactions/steps/set_child_flag.rb
- lib/iiif_print/persistence_layer.rb
- lib/iiif_print/persistence_layer/active_fedora_adapter.rb
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
- spec/services/iiif_print/simple_schema_loader_decorator_spec.rb
- spec/transactions/hyrax/transactions/iiif_print_container_decorator_spec.rb
- spec/transactions/hyrax/transactions/steps/set_child_flag_spec.rb
This commit will add a transaction for the set_child_flag functionality that used to use a after_save callback for Valkyrie objects.
> 🎁 Add transaction for set_child_flag

- db/migrate/20181214181358_create_iiif_print_derivative_attachments.rb
- db/migrate/20190107165909_create_iiif_print_ingest_file_relations.rb
- db/migrate/20230109000000_create_iiif_print_pending_relationships.rb
Check if table exists before insisting the migration should run.
We had issues when running migrations in a different project because of an error that the table already existed. We fixed it manually but this should fix the source. 
ref: [slack convo](https://assaydepot.slack.com/archives/C0313NKG2DA/p1706031216382859)
> 🧹 Add table_exists? guard clauses to migrations

- app/transactions/hyrax/transactions/iiif_print_container_decorator.rb
Update IiifPrint to sniff out if Bulkrax has a transaction for update_with_bulk_behavior and create_with_bulk_behavior (check if the constants are defined); then inject accordingly.
Related Issue:
- https://github.com/samvera/bulkrax/issues/897
> :gift: adds reference and registers bulkrax transaction 

- app/indexers/concerns/iiif_print/file_set_indexer.rb
`Valkyrie` indexers favor `#to_solr`; `ActiveFedora` based indexers favor
`#generate_solr_document`.  However, `Valkyrie` indexers also implement
`#generate_solr_document` (see [`Hyrax::Indexers::ResourceIndexer`][1]).
So we shouldn't decorate both of them as that would introduce potential
double processing.
[1]: https://github.com/samvera/hyrax/blob/3a82b3d513047e270848cd394c97fa4ac60e5b14/app/indexers/hyrax/indexers/resource_indexer.rb#L66-L85
> ♻️ Favor #to_solr over #generate_solr_document

- config/initializers/simple_schema_loader.rb
- lib/iiif_print.rb
- lib/iiif_print/engine.rb
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
This fix will add a few more requires to the engine.rb file and also move the simple schema loader decorator to the valkyrie_adapter because when a valkyrie application is booting up, the schema path needs to be in place before loading the yaml.
> 🐛 Fix boot problem

- app/transactions/hyrax/transactions/iiif_print_container_decorator.rb
- app/transactions/hyrax/transactions/steps/set_child_flag.rb
This commit will fix names since it changed somewhere along the way. The set child flag was being called when IIIF Print was not being used which resulted in an error.  This commit will set the condition to only call if the HYKU_IIIF_PRINT env var is true.
otherwise an error like this occurs:
> 🧹 Correct transactions names and set condition

- lib/iiif_print/persistence_layer/active_fedora_adapter.rb
Looks like it was just misnamed.
> 🐛 Fix `ActiveFedora::SolrQueryBuilder`

- app/listeners/iiif_print/listener.rb
This commit will add a reindex after the child work has been saved.
> 🧹 Reindex the child work after save

- app/services/iiif_print/manifest_builder_service_behavior.rb
- lib/iiif_print/configuration.rb
- lib/iiif_print/persistence_layer/active_fedora_adapter.rb
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
This commit corrects a typo in the configuration file and corrects the `.find_parents` method to be called on `Hyrax.query_service` instead. We also correct the method signature for `ValkyrieAdapter.solr_query` so it works with Ruby 3.0.0+ as well as its call.
> 🧹 Make valkyrie file sets show in uv

- Gemfile.lock
- app/transactions/hyrax/transactions/steps/conditionally_destroy_children_from_split.rb
- app/transactions/hyrax/transactions/steps/delete_all_file_sets_decorator.rb
- lib/iiif_print.rb
- lib/iiif_print/engine.rb
- lib/iiif_print/persistence_layer.rb
- lib/iiif_print/persistence_layer/active_fedora_adapter.rb
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
- lib/iiif_print/split_pdfs/destroy_pdf_child_works_service.rb
- spec/iiif_print/split_pdfs/destroy_pdf_child_works_service_spec.rb
- spec/transactions/hyrax/transactions/steps/conditionally_destroy_children_from_split_spec.rb
This commit will add an override for the `DeleteAllFileSets` step so we can insert the `iiif_print_conditionally_destroy_spawned_children` with args, we want to pass in the user so we can publish it to any relevant listeners.  We also implement the valkyrie way of deleting split child works in the `destroy_children_split_from` method.
> 🎁 Implement delete work for valyrie adapter

- lib/iiif_print/persistence_layer/active_fedora_adapter.rb
This relates to the fact that `Hyrax::SolrService` does not behave the same way (for earlier versions of Hyrax).
Related to:
- https://github.com/samvera/hyrax/pull/6677
> 🎁 Favor ActiveFedora::SolrService for Fedora adapter

- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
Refs https://github.com/scientist-softserv/hykuup_knapsack/issues/187
Deleting a work with a PDF file failed with a iiif_print error.
Deleting a work succeeds.
> 🐛 Disable rubocop for necessary parameter name

- config/metadata/child_works_from_pdf_splitting.yaml
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
21100a9f5b9c53bd3649518d4f9e39f93699cbb5
If ever the original_file hasn't been set, we want to guard against a
NoMethodError for NilClass.
2e4af9281cfd4a38aacfeae4ded42f10ace6763f
Because we have the form keys when the work gets created, `is_child` is
set to `''` and not `nil`. This causes any queries that look for
`is_child` being `nil` to not work.
> A few bug fixes

- lib/iiif_print/base_derivative_service.rb
Adds lonely operator per Rob's recommendation for defensive coding, even if, ideally, original_file shouldn't be nil.
We originally noticed an error when running iiif print split locally, from Hyku. 
```
NoMethodError (undefined method `image?' for nil:NilClass):
/usr/local/bundle/bundler/gems/iiif_print-675115934432/lib/iiif_print/base_derivative_service.rb:36:in `valid?'
```
> 🐛 Add lonely operator for defensive coding

- config/metadata/child_works_from_pdf_splitting.yaml
This is a partial fix for https://github.com/scientist-softserv/hykuup_knapsack/issues/240 and is tied in with a change in hyrax to support `display: false`
IiifPrint custom terms always appear on resource forms.
IiifPrint custom terms can be hidden via yaml `display: false` in the form definition.
<details>
<summary>Screenshots</summary>
</details>
> Hide custom terms from resource forms

- lib/iiif_print/configuration.rb
#lease_release_date is not a valid method so threw an error when running jobs to create relationships. Replace method with #lease_expiration_date.
Valid lease methods include:
```
parent_work.lease.methods.grep(/lease/)=>
[:visibility_after_lease=,
:lease_history=,
:lease_expiration_date,
:lease_expiration_date=,
:lease_history,
:visibility_after_lease,
:visibility_during_lease,
:visibility_during_lease=]
```
Jobs seemed to have split but create relationships failed, so it doesn't look like it worked.  
[ref](https://dev.pals.test/dashboard/my/works?locale=en)
Error from the server
> Replace #lease_release_date with #lease_expiration_date

- .github/workflows/build-lint-test-action.yaml
- app/services/iiif_print/simple_schema_loader_decorator.rb
- lib/iiif_print/engine.rb
As of Hyrax `9d8d5f8`, there is now a configuration for the `Hyrax::SimpleSchemaLoader` that allows us to do away with the need for a decorator.  I'm leaving it there for applications that aren't at `9d8d5f8` yet but guard it.
Ref:
- https://github.com/samvera/hyrax/commit/9d8d5f8dad116f9143e985e57ed26fd2543d4ec6
> ⚙️ Utilize Hyrax's schema search paths config

- app/indexers/concerns/iiif_print/child_work_indexer_decorator.rb
- app/models/concerns/iiif_print/solr_document_decorator.rb
- app/presenters/iiif_print/iiif_manifest_presenter_factory_decorator.rb
- app/presenters/iiif_print/work_show_presenter_decorator.rb
- app/services/iiif_print/manifest_builder_service_decorator.rb
- lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb
- lib/iiif_print/lineage_service.rb
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
- spec/factories/newspaper_page_solr_document.rb
- spec/models/solr_document_spec.rb
- spec/presenters/iiif_print/iiif_manifest_presenter_factory_decorator_spec.rb
Refs https://github.com/scientist-softserv/adventist_knapsack/issues/817
IiifPrint previously updated `member_ids` to include the child work's filesets. After Valkyrization, this resulted in the inclusion of both the pages & child works in the items list. By removing the override of `member_ids` and indexing `descendent_member_ids_ssim`, we now separated the inclusion of the descendent's filesets to only those situations where the behavior is desired.
Additionally, searching from the parent work was broken because the PDF files do not have text extraction and were returning invalid results.
- Child works & child filesets both show in items list.
- Universal Viewer text search did not work at the parent work level. 
- Only child works show in items list.
- Universal viewer shows each page …
> Remediate fileset duplication in items list

- app/helpers/iiif_print/iiif_helper_decorator.rb
- app/models/concerns/iiif_print/solr_document_decorator.rb
- app/views/catalog/_index_header_list_default.html.erb
WIP
Refs: https://github.com/scientist-softserv/adventist_knapsack/issues/769
> I769 snippets rework

- lib/iiif_print/image_tool.rb
- Added sync to convert method
- Adjusted im_identify in image_tool to set specific resource constraints on memory, map, and disk, reducing risk of process termination.
- This change addresses out-of-memory and out-of-sync issues when processing high-resolution images in ValkyrieCreateDerivativesJob.
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/856
> :bug: Fix image processing issue

- lib/iiif_print/configuration.rb
- lib/iiif_print/image_tool.rb
- Added environment variable support for ImageMagick memory, map, and disk limits in the `im_identify` method
- Falls back to imagemagick-6-policy.xml defaults if no configuration is provided
- Improves flexibility and control over resource usage during image processing
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/867
> i876 - Make memory, map, and disk limits in `im_identify` configurable

- app/jobs/iiif_print/jobs/child_works_from_pdf_job.rb
- lib/iiif_print/split_pdfs/child_work_creation_from_pdf_service.rb
> Fix lint errors

- app/models/iiif_print/iiif_search_decorator.rb
This commit will constrain the IIIF search to only search the file sets of a work.  This way applications that use all_text_tsimv for both the file sets and work (to support snippets) will not have the work's text included in the search which would double the results.
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/199
Before:
After:
> 🐛 Search OCR on file sets only

- app/controllers/iiif_print/split_pdfs_controller.rb
- app/jobs/iiif_print/jobs/request_split_pdf_job.rb
- lib/iiif_print.rb
- lib/iiif_print/persistence_layer.rb
- lib/iiif_print/persistence_layer/active_fedora_adapter.rb
- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
There were a few pieces of the pdf resplitting process that were not fully valkyrized. 
- This commit valkyrizes the resplitting, and fixes a bug with removing the child works from the initial split.
- Note that this also fixes the connection to delete the spawned child works when the parent work is deleted.
Ref https://github.com/notch8/palni_palci_knapsack/issues/80
PDF resplitting had numerous errors
Using the PDF resplit button successfully removes prior child works and creates new ones
Deleting a work which has child works split from a PDF will also delete the child works.
<details>
Original work with "highlighted" child works:
After resplit (highlighted works were deleted & replaced with new child work)
Original child work no longer found
</details>
> Fix pdf resplitting

- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
The underscore was used to indicate that the parameter is not used in the method. This is a common pattern in Ruby and is used to indicate that the parameter is not needed for the method to function correctly.
However, this does not work with keyword arguments, so this change disables this rubocop test instead.
> Add rubocop disable for unused parameter

- Gemfile.lock
- lib/iiif_print/version.rb
Prepare for release of v3.0.3
This bump up version fixes an error caused by accommodating rubocop.
> Update version to v3.0.3

- lib/iiif_print/persistence_layer/valkyrie_adapter.rb
I accidentally merged in a lint offense. This PR corrects it:
> 💄 fix rubocop offense
